### ISSUE TITLE
Dash Provider

### ISSUE THREAD

**Issue by mihar-22** [vidstack/player#17]
## Tasks

- [ ] Implement Dash Provider
- [ ] Installation Docs (https://www.vidstack.io/docs/player/getting-started/installation)
- [ ] Provider Docs (https://www.vidstack.io/docs/player/providers/dash)

## References

- https://github.com/Dash-Industry-Forum/dash.js
- https://github.com/vime-js/vime/tree/master/core/src/components/providers/dash

**Comment by iSuslov** [comment]
Hey @mihar-22, is there any priority for this feature?

**Comment by mihar-22** [comment]
Not at the moment @iSuslov, we already have a lot to do and Dash is not the highest priority for us (at this time). Our [player roadmap](https://github.com/orgs/vidstack/projects/1/views/1?sortedBy%5Bdirection%5D=asc&sortedBy%5BcolumnId%5D=Milestone&groupedBy%5BcolumnId%5D=Milestone) covers what we're focused on for future reference.

**Comment by WardPearce** [comment]
Any updates on this? Roadmap link no longer works

**Comment by justin13888** [comment]
Looking for update here too! Need DASH if I'm moving over
