### ISSUE TITLE
Community Skin

### ISSUE THREAD

**Issue by mihar-22** [vidstack/player#73]
## Tasks

- [x] Implement https://github.com/vidstack/player/discussions/702
- [x] Installation Docs (https://www.vidstack.io/docs/player/getting-started/installation)
- [x] Skins Docs (https://www.vidstack.io/docs/player/styling/skins)

## References

- https://github.com/vime-js/vime/tree/master/core/src/components/ui/default-ui
- https://github.com/vime-js/vime/tree/master/core/src/components/ui/settings/default-settings
- https://github.com/vime-js/vime/tree/master/core/src/components/ui/controls/default-controls
