### ISSUE TITLE
Live Stream Support

### ISSUE THREAD

**Issue by mihar-22** [vidstack/player#88]
## Tasks

- [x] Complete #16.
- [ ] Complete #17.
- [ ] Design and implement an interface for live streams on the player.
- [ ] Add support for live HLS streams and test it.
- [ ] Add support for live DASH streams and test it.
- [ ] Investigate which components will be effected by a live stream and create a seperate issue for each to add live support to it.
